config/routes.rb
Rails.application.routes.draw do
  resources :alerts, only: [:index, :destroy]

  namespace :alerts do
    resources :custom, except: [:index, :destroy]
  end

  resources :items, only: [:index, :show, :destroy, :update]

  get 'TalonRO/search', to: 'talon_ro#search', as: :talon_ro_search

  root 'items#index'
end

app/models/alert.rb
class Alert < ApplicationRecord
  OPERATIONS = { 
    greater_than_or_equal_to: '>=',
    less_than_or_equal_to: '<='
  }

  belongs_to :item
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buying_offer.rb
class BuyingOffer < Offer
end

app/models/custom_alert.rb
class CustomAlert < Alert
  validates_presence_of :price, :item_id, :operation, :offer_type

  def should_fire_for_offer? offer
    offer.item_id == item_id and
      offer.type == offer_type and
      offer.price.send(operation, price)
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :offers, dependent: :destroy

  # TODO: add the market to uniqueness scope
  validates :name, uniqueness: true

  scope :tracked, -> { where(track_sellers: true).or(Item.where(track_buyers: true)) }
end

app/models/offer.rb
class Offer < ActiveRecord::Base

  belongs_to :item

  validates :item_name, uniqueness: { scope: [
    :slots,
    :refinement,
    :cards,
    :price,
    :vendor,
    :shop_title,
    :map_location,
    :type
  ]}

  def full_item_name
    refinement_string = refinement? ?  "+#{refinement}" : ""
    slots_string = slots? ? "[#{slots}]" : ""
    [refinement_string, item_name, slots_string].join(' ').strip
  end
end

app/models/offer_observer.rb
class OfferObserver < ActiveRecord::Observer
  def after_create(offer)
    Alert.where(item_id: offer.item_id).each do |alert|
      if alert.should_fire_for_offer?(offer)
        AlertMailer.custom_email(offer.id).deliver_later
      end
    end
  end
end

app/models/selling_offer.rb
class SellingOffer < Offer
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable
end

app/controllers/alerts/custom_controller.rb
class Alerts::CustomController < AlertsController
  before_action :set_alert, only: [:edit, :update]

  # GET /alerts/new
  def new
    @alert = CustomAlert.new
  end

  # POST /alerts
  # POST /alerts.json
  def create
    @alert = CustomAlert.new(alert_params)

    respond_to do |format|
      if @alert.save
        format.html { redirect_to alerts_url, notice: 'Alert was successfully created.' }
        format.json { render :show, status: :created, location: @alert }
      else
        format.html { render :new }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alerts/1
  # PATCH/PUT /alerts/1.json
  def update
    respond_to do |format|
      if @alert.update(alert_params)
        format.html { redirect_to alerts_url, notice: 'Alert was successfully updated.' }
        format.json { render :show, status: :ok, location: @alert }
      else
        format.html { render :edit }
        format.json { render json: @alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    @alert.destroy
    respond_to do |format|
      format.html { redirect_to alerts_url, notice: 'Alert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_alert
      @alert = Alert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alert_params
      params.require(:custom_alert).permit(:item_id, :price, :operation, :offer_type)
    end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController
  # GET /alerts
  # GET /alerts.json
  def index
    @alerts = Alert.all
  end

  # DELETE /alerts/1
  # DELETE /alerts/1.json
  def destroy
    Alert.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to alerts_url, notice: 'Alert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :update]

  def index
    @items = Item.order(updated_at: :desc)
  end

  def show
  end

  def destroy
    Item.destroy(params[:id])

    respond_to do |format|
      format.html { redirect_to items_path }
    end
  end

  def update
    @item.update_attributes(item_params)
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:track_sellers, :track_buyers)
  end
end

app/controllers/talon_ro_controller.rb
class TalonROController < ApplicationController
  def search
    notifier = EmailNotifier.new
    @offers = OffersGrabber.new(params[:item_name], params[:offers_type], notifier).offers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_back options
    url = options.fetch(:url, :back)
    label = "← " + options.fetch(:label, 'back')
    link_to label, url 
  end
end

app/helpers/talon_ro/selling_shops_helper.rb
module TalonRO::SellingShopsHelper
end

app/views/alerts/custom/_form.html.erb
  <%= form_for(alert, url: alert.new_record? ? alerts_custom_index_url : alerts_custom_url(alert), html: { class: 'pure-form pure-form-stacked' }) do |f| %>
    <% if alert.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(alert.errors.count, "error") %> prohibited this alert from being saved:</h2>

        <ul>
          <% alert.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <fieldset>
      <div class="pure-g">
        <div class="pure-u-1">
          <%= f.label :item_id, class: 'pure-u-1' %>
          <%= f.collection_select :item_id, Item.tracked, :id, :name, { prompt: true } , class: 'pure-u-1' %>
        </div>

        <div class="pure-u-1-3">
          <div class="pure-g">
            <%= f.label :operation, 'Price', class: 'pure-u-9-24' %>
            <%= f.collection_select :operation, Alert::OPERATIONS, :last, :last, {}, class: 'pure-u-14-24' %>
          </div>
        </div>

        <div class="pure-u-2-3">
          <div class="pure-g">
            <%= f.label :price, 'than', class: 'pure-u-5-24' %>
            <%= f.number_field :price, placeholder: 'Price in Zeny', class: 'pure-u-19-24' %>
            </div>
        </div>

        <%# TODO: set the radio_button by default %>
        <div class="pure-u-1">
          <div class="pure-g">
            <%= label_tag 'selling-offer-option', class: 'pure-u-1-2 pure-radio' do %>
              <%= f.radio_button :offer_type, 'SellingOffer', id: 'selling-offer-option' %>
              Selling Offers
            <% end %>
            <%= label_tag 'buying-offers-option', class: 'pure-u-1-2 pure-radio' do %>
              <%= f.radio_button :offer_type, 'BuyingOffer', id: 'buying-offers-option' %>
              Buying Offers
            <% end %>
          </div>
        </div>

        <div class="pure-u-1 pure-u-lg-1-5">
          <%= f.submit class: 'pure-button pure-button-primary pure-u-1' %>
        </div>
      </div>
    </fieldset>
  <% end %>

app/views/alerts/edit.html.erb
<h1 class="content-head">Editing Alert</h1>

<%= render 'form', alert: @alert %>

<%= link_to_back url: alerts_path %>

app/views/alerts/index.html.erb
<h1 class="content-head">Alerts</h1>

<table class="pure-table pure-table-striped">
  <thead>
    <tr>
      <th>Item</th>
      <th>Offer type</th>
      <th colspan="2">Price</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @alerts.each do |alert| %>
      <tr>
        <td><%= alert.item.name %></td>
        <td><%= alert.offer_type %></td>
        <td><%= alert.operation %></td>
        <td><%= alert.price %></td>
        <td><%= link_to 'Edit', edit_alerts_custom_path(alert) %></td>
        <td><%= link_to '×', alert_path(alert), class: 'pure-button button-danger button-small',method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Custom Alert', new_alerts_custom_path, class: 'pure-button pure-button-primary pure-u-1 pure-lg-1-5' %>

<br>
<br>

<%= link_to_back url: root_path %>

app/views/alerts/new.html.erb
<h1 class="content-head">New Alert</h1>

<%= render 'form', alert: @alert %>

<%= link_to_back url: alerts_path %>

app/views/alerts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @alert.item %>
</p>

<p>
  <strong>Price:</strong>
  <%= @alert.price %>
</p>

<p>
  <strong>Operation:</strong>
  <%= @alert.operation %>
</p>

<p>
  <strong>Offer type:</strong>
  <%= @alert.offer_type %>
</p>

<%= link_to 'Edit', edit_alert_path(@alert) %> |
<%= link_to 'Back', alerts_path %>

app/views/items/delete.html.erb
<h1>Items#delete</h1>
<p>Find me in app/views/items/delete.html.erb</p>

app/views/items/index.html.erb
<h1 class="content-head">Items</h1>

<%= render 'shared/search_market_form', search_url: talon_ro_search_path%>

<table class="pure-table pure-table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tracking Sellers</th>
      <th>Tracking Buyers</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.name, item_path(item) %></td>
        <td class="is-center">
          <%= form_for item, namespace: item.id, html: { class: 'pure-form' } do |f| %>
            <%= f.label :track_sellers, class: 'pure-checkbox' do %>
              <%= f.check_box :track_sellers, onclick: "$(this.form).submit()" %>
            <% end %>
          <% end %>
        </td>
        <td class="is-center">
          <%= form_for item, namespace: item.id, html: { class: 'pure-form' } do |f| %>
            <%= f.label :track_buyers, class: 'pure-checkbox' do %>
              <%= f.check_box :track_buyers, onclick: "$(this.form).submit()" %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to '×', item_path(item), class: 'button-danger button-small pure-button', method: :delete, data: { confirm: 'All offers will be delete as well. Are you sure?' } %>
    <% end %>
  </tbody>
</table>

app/views/items/show.html.erb
<h1 class="content-head"><%= @item.name %></h1>
<div id="chart_div" data-offers="<%= @item.offers.to_json(methods: :type) %>"></div>
<legend>Offers</legend>
<hr />
<%= render 'offers/table', offers: @item.offers %>
<br>
<%= link_to "←  all items", items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>TheMarketRogue</title>
        <%= stylesheet_link_tag    'http://yui.yahooapis.com/pure/0.6.0/pure-min.css', media: 'all', 'data-turbolinks-track' => true %>
        <%= stylesheet_link_tag    'http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css', media: 'all', 'data-turbolinks-track' => true %>
        <!--[if lte IE 8]>
          <%= stylesheet_link_tag  'http://yui.yahooapis.com/pure/0.6.0/grids-responsive-old-ie-min.css', media: 'all', 'data-turbolinks-track' => true %>
        <![endif]-->
        <!--[if gt IE 8]><!-->
        <%= stylesheet_link_tag  'http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css', media: 'all', 'data-turbolinks-track' => true %>
        <!--<![endif]-->
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

        <meta name="description" content="A tarcking tool for Ragnarok market">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="utf-8">

        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'https://www.gstatic.com/charts/loader.js', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
      <div class="header">
        <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">
          <%= link_to "TMR", root_path, class: 'pure-menu-heading' %>

          <ul class="pure-menu-list">
            <li class="pure-menu-item">
              <%= link_to "Items", root_path, class: 'pure-menu-link' %>
            </li>
            <li class="pure-menu-item">
              <%= link_to "Alerts", alerts_path, class: 'pure-menu-link' %>
            </li>
          </ul>
        </div>
      </div>

      <div class="content-wrapper">
        <div class="content">
          <%= yield %>
        </div>
        <div class="footer l-box is-center">
            The Market Rogue
        </div>
      </div>
    </body>
</html>

app/views/offers/_table.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cards</th>
      <th>Price</th>
      <th>Amount</th>
      <th>Vendor</th>
      <th>Shop Title</th>
      <th>Coords</th>
    </tr>
  </thead>
  <tbody>
    <% offers.each do |offer| %>
    <tr>
      <td><%= link_to offer.full_item_name, item_path(offer.item_id) %></td>
      <td><%= offer.cards %></td>
      <td><%= offer.price %></td>
      <td><%= offer.amount %></td>
      <td><%= offer.vendor %></td>
      <td><%= offer.shop_title %></td>
      <td><%= offer.map_location %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_search_market_form.html.erb
<%= form_tag(search_url, method: :get, class: 'pure-form') do %>
  <fieldset>
    <div class="pure-g">
      <div class="pure-u-1">
        <%= text_field_tag :item_name, params[:item_name], class: 'pure-input-1',placeholder: 'Search for an item' %>
      </div>
      <div class="pure-u-1">
        <%= label_tag 'selling-offer-option', class: 'pure-radio' do %>
          <%= radio_button_tag :offers_type, 'SellingOffer', params[:offers_type].nil? ? true : params[:offers_type] == 'SellingOffer', id: 'selling-offer-option' %>
          Selling Offers
        <% end %>
        <%= label_tag 'buying-offers-option', class: 'pure-radio' do %>
          <%= radio_button_tag :offers_type, 'BuyingOffer', params[:offers_type] == 'BuyingOffer', id: 'buying-offers-option' %>
          Buying Offers
        <% end %>
      </div>
      <div class="pure-u-1 pure-u-lg-1-5">
        <%= submit_tag 'Search', class: 'pure-button pure-button-primary pure-u-1' %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/talon_ro/search.html.erb
<h1 class="content-head">Selling Shops</h1>

<%= render 'shared/search_market_form', search_url: talon_ro_search_path %>

<br>

<%= render 'offers/table', offers: @offers %>

<br>

<%= link_to "← back", root_path %>